# Define the base image
FROM node:18

# Set the working directory in the Docker image
WORKDIR /usr/src/app

# Copy the rest of the application to Docker image
COPY index.js ./
COPY src/services/fargate.js src/services/prompt.js ./src/services/

RUN npm install openai 

# Install dependencies
RUN npm install readline
RUN npm install aws-sdk

# Command to run the application
CMD [ "node", "index.js" ]
