
# Use a Node.js base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm ci --production

# Install Twilio
RUN npm install twilio
RUN npm install openai

# Copy the application code to the container
# COPY index.js services/gpt3.js services/twilio.js ./
COPY index.js ./
COPY services/gpt3.js services/twilio.js ./services/

# Specify the command to run your application
CMD [ "node", "index.js" ]
