# Use a Node.js base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm ci --production

# Install Twilio
RUN npm install twilio

# Copy the application code to the container
COPY handler.js ./

# Specify the command to run your application
CMD [ "node", "handler.js" ]
